### ISSUE TITLE
API randomly crashes on read sometimes?

### ISSUE THREAD

**Issue by Berrescuda** [BenningtonCS/GFS#100]
Error example:

Traceback (most recent call last):
  File "client.py", line 25, in <module>
    API.read(filename, byteOffSet, bytesToRead)
  File "/home/cgilbert-espada/GFS/API.py", line 323, in read
    s.close()

**Comment by Berrescuda** [comment]
I think this happens when the user inputs a byte offset greater than a certain amount.

**Comment by edaniszewski** [comment]
This may be able to be handled in the master, so the API doesn't even need to worry about it. The master would need to know what the max byte offset for a chunk is, though.. that is, if a chunk can hold 1000 bytes, and it currently only has 500 bytes, the master would need to know there are only 500 bytes left..
Since as of now, the master is not keeping track of bytes in a file, this may require the chunkservers to check how many bytes are in the file before it reads from them, and if the requested ending byte offset is greater than the existing ending byte offset, just send up to the existing ending byte offset. There should be a group discussion at the very least.

**Comment by acencini** [comment]
discussion warranted but share the opinion that if chunk is 400 bytes and
user requests 500, you just give 'em 400 and that's all you get charlie.

On Thu, Nov 14, 2013 at 1:17 AM, Erick Daniszewski <notifications@github.com

**Comment by ltraynor** [comment]
I just tested read and it worked fine

**Comment by edaniszewski** [comment]
from my testing of the read functionality, I didn't see any strange reads/errors thrown (besides the one where input offset is greater than possible which is handled in the commit referenced above).  The reading of files is printed to the console in an slightly odd way, but reading across chunks, reading within a chunk, and reading to the end of a file all seemed to work and not throw any errors for me as well.

**Comment by Berrescuda** [comment]
This is fine now, error fixed.
