### ISSUE TITLE
implement youtube over GFS

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#113]
this would be a great demo.  upload functionality and view functionality.  will likely need buffering of a block or two just in case of slow read or failure.

**Comment by rohailaltaf** [comment]
Bennington File Share currently under construction. I have successfully been able to create a web interface for CREATE and APPEND. Working on READ

**Comment by rohailaltaf** [comment]
After an intense 3 day coding session, the online file share seems to be coming along really well. Chunk size is now set to 64mb and I have tested files up to 512mb in size without any issues. Streaming video is possible since the file is read out of the system in chunks so theoretically a large video file can start playing without having the need to wait for the read to complete. An online file manager is also sort of in place. Going to add UI elements and polish it up a bit. Still looking for a suitable player to embed on the page. I think I've found one. How did I accomplish this? Look:

![img_6826](https://f.cloud.github.com/assets/5447911/1648327/a963e5bc-598a-11e3-90a9-b08a5dcd608a.JPG)

**Comment by acencini** [comment]
i see you have made a few trips to the hot bar.  wise choice.

**Comment by acencini** [comment]
also, thank you for your credit card # - i've ordered a few things, hope that's ok :+1:

**Comment by rohailaltaf** [comment]
gone are the days when cell phone cameras were blurry

**Comment by acencini** [comment]
this is sufficient
