### ISSUE TITLE
chunkserver complaining in production

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#131]
2013-11-20 13:50:19,272 ERROR : [Errno 2] No such file or directory: '/data/gfsbin/Chunks/47'
2013-11-20 13:50:19,289 ERROR : [Errno 2] No such file or directory: '/data/gfsbin/Chunks/48'

(10.10.117.11)

**Comment by edaniszewski** [comment]
Are there any details about how this originated? (ie on a create, append, read, etc) It seems likely that it is being thrown by the chunkserver code since the chunkserver logs exceptions in this way, but it is difficult to debug what is happening as the chunkserver debug gives no additional details about the failure..

**Comment by acencini** [comment]
this is just showing up constantly in  monitoring

On Wed, Nov 20, 2013 at 9:14 AM, Erick Daniszewski <notifications@github.com

**Comment by edaniszewski** [comment]
I believe this is fixed now. When I updated the scrubber last night and put it on the master, I forgot to push the changes to chunkserver.py to the chunkservers, so the problem that caused this was not actually fixed.

I updated the chunkserver code on the RPIs, and ran a few creates/deletes and it seems to be working now. I haven't seen any new errors arise on the chunkserver logs since restarting the chunkservers.

**Comment by acencini** [comment]
great.  we should make it easier to monitor and debug these issues - good
investigation, find and fix.

**Comment by edaniszewski** [comment]
since this issue appears to be fixed, I'm going to close it and open issues for release to improve debugging and make monitoring easier

**Comment by acencini** [comment]
perfect
