### ISSUE TITLE
For all - improve debugging/error handling

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#134]
Currently, most parts have some level of debugging and error handling. It would be worthwhile for everyone to go back through their code and ensure that the debugging/error messages are descriptive and helpful for finding and fixing issues (no generic messages)

Additionally, it would be prudent to have handling for errors, if possible. It seems that lots of the code currently just throws an error message for most exceptions - could the exceptions be automatically handled? could retrys help?

**Comment by acencini** [comment]
one question (i have not reviewed this part of the code recently)

do we do request logging?  for example, API->master, master->API, API->chunkerver, etc. - this would just be for deubgging/tracing but would include the IP of the requestor, what they were doing and whether it succeeded.  similar to HTTP access logging.  this might help with some research questions (maybe?) but if you think about it, would also be crucial in a production system because you do want to have data on system usage!

**Comment by acencini** [comment]
are we in a position where it is futile to pursue this further?  if so either close or punt to future release

**Comment by edaniszewski** [comment]
Yeahhhh, probably. We should consider this as we do anything, but leaving it as an open issue may be futile at this point..
