### ISSUE TITLE
have httpServer.py running on chunkservers after tests are done

### ISSUE THREAD

**Issue by rohailaltaf** [BenningtonCS/GFS#157]
@edaniszewski we talked about this in the lab. Can you just let me know when your tests are done so I can start them?

**Comment by edaniszewski** [comment]
Will do, it will probably be sometime Wednesday during/after class when these things finish. Because the experimental design has me appending ~80MB for each append (100 appends for 1 test cycle, x about 5 test cycles per chunk size x 6 different chunk sizes). Its just taking a while for each test to run its course, but I'll let you know!

**Comment by acencini** [comment]
fixed - verified
