### ISSUE TITLE
API/master - improve failure handling on create

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#70]
As of now, if the create command can throw back an error to the API if something went south, but the API/master do not yet have a way of specifying exactly what the error was.. 

maybe the master could send an error message? ==>  FAIL | "file name already exists"

**Comment by acencini** [comment]
this is a good suggestion

for efficiency and coding ease, rather than passing an error string in the protocol, why not pass a code - fewer bytes over the wire, and you can have a map of codes->strings in the API, and both consumers of the API and internally within the API it will be easier to code around certain errors without having to rely on a particular string.

**Comment by ltraynor** [comment]
done
