### ISSUE TITLE
consider experiment design for poster

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#77]
what shall ye measure?

**Comment by AlliumApotheosis** [comment]
I don't know. We're working on it.

**Comment by edaniszewski** [comment]
One thing I've been thinking about is ways of optimizing the database. The GFS paper states: 

> "Since metadata is stored in memory, master operations are fast. Furthermore, 
> it is easy and efficient for the master to periodically scan through its entire state 
> in the background."

I'm wondering if the way the metadata is being stored can be changed so that lookups take up less memory (and can therefore store more), and be faster. I have a feeling the answer yes, but finding out how to make it faster would be a fun experiment, even if it is not the main experimental design overall.

**Comment by acencini** [comment]
could alternate storage structures be considered?  e.g. using a DHT as the
master so you do not need to know a single master but rather just any old
node out there.  that is kind of an insane design but almost obviates the
need for recovery/log in the master since the DHT should never be able to
go down and if it does, it could be reseeded by a client.  routing to
master would be the annoying part as you may make some number of network
hops per master request to find out where you're going.  would add some
complexity to the design.  but alternate db structures and measuring would
be good, though amdahl's law (roughly) states speedup is greatest in the
part of the program doing the most work.  is db lookup the slow part or is
there something else (e.g. anticipating future accesses and prefetching
data from master) that may help even more?

On Sun, Nov 17, 2013 at 1:43 AM, Erick Daniszewski <notifications@github.com

**Comment by acencini** [comment]
some other test ideas - throughput (write/read), scalability (test on many nodes), as well as lazy allocation strategy, and other questions you come up with.

**Comment by acencini** [comment]
also, it may make sense to replicate one or two of google's experiments from the paper.

**Comment by acencini** [comment]
by "may" i mean it should be done :)

**Comment by edaniszewski** [comment]
It would be interesting to try and replicate the GFS experiment detailed in section 6.25 - Recovery Time

So far, the only experiments I have done looking at chunk recovery/replication from disconnected chunkservers used: 1 master, 4-6 chunkservers, and no shadow masters. All the chunk sizes were small, around 12,000 bytes. 

It would be interesting to see if our recovery system could scale up to 10s if not 100s of machines, all with large amounts of chunk data, to see if our recovery time is slower, faster, or about the same as GFS.

**Comment by acencini** [comment]
:poop:

**Comment by edaniszewski** [comment]
I think as of now, unless black magic is invoked injecting more hours in the day, the biggest constraint for our testing is time. Since the current tests take a reasonable amount of time to complete a cycle, it would be difficult to schedule in additional tests. As it stands, what is being tested:
1. Chunk Size. 
   - Does changing the chunk size result in better performance/storage?

For this, I am running a script to create, append, read, delete, and scrub (cards cycle). It logs the time it takes for each action to complete. This can be used for calculating general throughput measures later.. The append size is 80 MB (and thus the read size is also). This cards cycle runs 100 times per test, and ideally each chunk size will have at least 5 tests run. This will be done for chunk sizes 2MB, 4MB, 8MB, 16MB, 32MB, 64MB. 80MB is larger than all of these, so it will make sure for each size, multi-chunk append is utilized. 
1. Scaling
   - Does our system scale well?

For this, the same test that is being utilized above is being run, with the append size 80 MB and running at least 1 test cycle for all chunk sizes mentioned above. What this will do is provide a line of comparison between our local system and a system with 50 nodes. Hopefully, the timings will be very close, indicating that as the system scales, there is no loss in performance. It would be great if there was a gain in performance, but we will have to wait and see!

If there is any time, I think it would be prudent to try and replicate a test from the paper, but that may be difficult with our time constraint, and there may not be enough room on the poster for all these tests as it is. I have begun to write the poster in the down time between test cycles and so far have about half of it filled with mostly intro, background, and methods. I've realized that it is difficult to be concise while giving a solid overview of the system and its components to allow for a better understanding of the data.. (explaining chunks, chunkservers, master, api, distributed file systems, etc). Its a bit more text heavy than I would like, I think, but we can go through and edit it down as a class during our lab session.

**Comment by AlliumApotheosis** [comment]
Design Considered.
