### ISSUE TITLE
Master - Fix Ghost message bug

### ISSUE THREAD

**Issue by Berrescuda** [BenningtonCS/GFS#98]
The master routinely receives an empty string, apparently from nowhere, someone should hunt this down and fix it.

**Comment by edaniszewski** [comment]
@Kgespada 's commit e47f774a7a9696cd62d6c0130f9e9eefb1643e90 addresses this. Instead of having the thread crash now, it will end gracefully. 

The ghost message still exists, however. I have a feeling it resides in either functionLibrary.recv() or functionLibrary.send()

#72 -- See Andrew's comment about acks.. they may be unnecessary here, and they may be the cause of/contribute to the problem.

**Comment by edaniszewski** [comment]
This issue has been resolved with issue #105  

after running tests I no longer see the ghost messages.
